### ISSUE TITLE
Link update...

### ISSUE THREAD

**Issue by rod-trent** [dcaddick/gsd_public#6]
In the Validate and Test section: How to Generate Microsoft Sentinel Incidents for Testing and Demos https://azurecloudai.blog/2021/05/24/how-to-generate-azure-sentinel-incidents-for-testing/

Link has been updated to: https://rodtrent.substack.com/p/how-to-generate-microsoft-sentinel

**Comment by dcaddick** [comment]
Thanks Rod, these can be done by a Pull Request 😜
Love your work BTW
