### ISSUE TITLE
minor update

### ISSUE THREAD

**Issue by Cosmicspatula** [dcaddick/gsd_public#7]
for "Local Australian E8 Guides - Microsoft Service Trust Portal has the local Essential 8 guides https://aka.ms/e8guides here you will find the PDF's covering the following specifics - you will need to sign in using your own Tenant ID to access the docs", you do not need to sign in.  However for IRAP etc, you do need to sign in.

**Comment by dcaddick** [comment]
Thanks Tania, updated
